name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: setup git config
        run: |
          git config user.name "GitHub Bot"
          git config user.email "<nikita+github-bot@tokarch.uk>"

      - name: fetch the latest ghost version
        run: |
          ./update.sh

      - name: commit
        if: ${{ success() }}
        run: |
          git add -A
          git commit -m "Updated ghost version"
          git push origin master
