name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: setup git config
        run: |
          git config user.name "GitHub Bot"
          git config user.email "<nikita+github-bot@tokarch.uk>"

      - name: fetch and update to the latest ghost version
        id: update
        run: |
          ./update.sh

      - name: commit
        if: ${{ steps.update.outputs.updated > 0 }}
        run: |
          git add -A
          git commit -m "Update to ${{ steps.update.outputs.ghost }}, ghost-cli ${{ steps.update.outputs.ghost-cli }}"
          git push origin master
